const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
  FETCH_ITEM_START: 'FETCH_ITEM_START',
  FETCH_ITEM: 'FETCH_ITEM',
  FETCH_ITEM_FAILURE: 'FETCH_ITEM_FAILURE'
};

export default ShopActionTypes;